In [1]:
!pip install numpy
import numpy as np

Defaulting to user installation because normal site-packages is not writeable


# Sıfırlardan oluşan dizi

In [2]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Float tipi 1'den oluşan 3x5'lik matris

In [3]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Integer 4'lerden oluşan 4x4'lük matris

In [4]:
np.full((4,4), 4, dtype=int)

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

# 0'dan başlayıp (0 dahil) üçer üçer 31'e dek artan dizi

In [5]:
np.arange(0, 31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

# 0 ile 1 arasında 10 tane değerden oluşan tek boyutlu dizi

In [6]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# Ortalaması 10, standart sapması 4 olacak şekilde 3x4'lük matris

In [7]:
np.random.normal(10, 4, (3,4))

array([[14.84689844, 22.97445285, 11.73547486, 13.21529386],
       [13.22583379, 10.44299108,  6.80109491, 13.07249499],
       [ 7.36647004, 14.94153061,  9.08985867,  5.4842987 ]])

# 0 ile 10 arasındaki rastgele integer değerlerden oluşan 5x5'lik matris

In [8]:
np.random.randint(0, 10, (5,5))

array([[8, 5, 2, 7, 6],
       [5, 0, 5, 5, 4],
       [6, 9, 9, 6, 1],
       [8, 1, 6, 6, 6],
       [4, 4, 4, 8, 9]])