In [2]:
import numpy as np

# NumPy Dizi Yeniden Şekillendirme

In [2]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
print(np.arange(1, 10).shape)

(9,)


In [4]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
print(np.arange(1,10).reshape((3,3)).shape)

(3, 3)


## Tek boyutlu diziyi (vektörü) iki boyutlu hale getirme

In [6]:
v = np.arange(1, 10)

In [7]:
print(v)

[1 2 3 4 5 6 7 8 9]


In [8]:
print(v.ndim)

1


### Yukarıda görüldüğü gibi v tek boyutlu ve 9 elemanlı bir dizi
Şimdi bu diziyi 2 boyutlu hale getirmek için `reshape` uygulayacağız

In [9]:
v_r = v.reshape((1,9))

In [10]:
print(v_r)

[[1 2 3 4 5 6 7 8 9]]


In [11]:
print(v_r.ndim)

2


# NumPy Dizi Birleştirme

In [12]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [13]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

## İki boyutlu matrisleri birleştirme

In [15]:
x_23 = np.array([[1, 2, 3],
                 [4, 5, 6]])
x_43 = np.concatenate([x_23, x_23])

In [18]:
print(x_23)
print(x_23.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [19]:
print(x_43)
print(x_43.shape)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
(4, 3)


### Görüldüğü üzere iki matris satır bazında birleştirildi
Böylece 2x3 iki matrisin alt alta koyulmasıyla 4x3 bir matris elde edildi. Şimdi sütun bazında birleştirme yapalım

In [22]:
x_26 = np.concatenate([x_23, x_23], axis=1)

In [23]:
print(x_26)
print(x_26.shape)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
(2, 6)


# NumPy Dizi Ayırma

In [24]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])

### x dizisini 3. elemana dek ayır, sonra 5. elemana dek ayır

In [26]:
np.split(x, [3, 5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

## İki boyutlu ayırma

In [28]:
m = np.arange(16).reshape(4,4)
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [31]:
ust, alt = np.vsplit(m, [2])

In [32]:
print(ust)

[[0 1 2 3]
 [4 5 6 7]]


In [33]:
print(alt)

[[ 8  9 10 11]
 [12 13 14 15]]


In [34]:
sol, sag = np.hsplit(m, [2])

In [35]:
print(sol)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [36]:
print(sag)

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# NumPy Dizi Sıralama

In [37]:
v = np.array([2, 1, 4, 3, 5])
print(v)

[2 1 4 3 5]


In [38]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [39]:
v.sort()

In [40]:
print(v)

[1 2 3 4 5]


## İki boyutlu dizi sıralama

In [41]:
n = np.random.normal(10, 4, (3, 3))

In [42]:
print(n)

[[ 3.3116903  15.9627824  11.02590338]
 [ 9.82691476 13.23646626 15.10133332]
 [ 8.9820192   4.0339741   8.7260658 ]]


### Dizinin satırlarını sırala: **axis = 1**

In [44]:
print(np.sort(n, axis = 1))

[[ 3.3116903  11.02590338 15.9627824 ]
 [ 9.82691476 13.23646626 15.10133332]
 [ 4.0339741   8.7260658   8.9820192 ]]


### Dizinin sütunlarını sırala: **axis=0**

In [45]:
print(np.sort(n, axis=0))

[[ 3.3116903   4.0339741   8.7260658 ]
 [ 8.9820192  13.23646626 11.02590338]
 [ 9.82691476 15.9627824  15.10133332]]


# Dizi Alt Kümeleri (Slicing)

In [3]:
a = np.arange(31, 41)
print(a)

[31 32 33 34 35 36 37 38 39 40]


### Baştan 3. elemana dek (3. dahil değil)

In [4]:
print(a[:3])

[31 32 33]


### 3. elemandan sona dek

In [5]:
print(a[3:])

[34 35 36 37 38 39 40]


### 1. elemandan başla, ikişer ikişer

In [6]:
print(a[1::2])

[32 34 36 38 40]


## Matriste slice işlemleri

### print( m [ SATIR, SÜTUN ] )

In [7]:
m = np.random.randint(10, size=(5, 5))
print(m)

[[7 1 9 5 8]
 [1 2 8 9 0]
 [5 2 2 0 4]
 [4 5 8 1 1]
 [5 3 1 6 7]]


### 0. sütunu seç

In [8]:
print(m[:, 0])

[7 1 5 4 5]


### 3. sütunu seç

In [9]:
print(m[:, 3])

[5 9 0 1 6]


### 2. satırı seç

In [10]:
print(m[2, :])

[5 2 2 0 4]


### İlk 3 satırı ve ilk 2 sütunu seç 

In [11]:
print(m[:3, :2])

[[7 1]
 [1 2]
 [5 2]]


### Ortadaki üç sütunu seç

In [13]:
print(m[:, 1:4])

[[1 9 5]
 [2 8 9]
 [2 2 0]
 [5 8 1]
 [3 1 6]]


## Alt kümeyi bağımsızlaştırma (copy)

In [15]:
a = np.random.randint(10, size=(4, 4))
print(a)

[[4 0 3 7]
 [9 1 6 3]
 [6 0 3 2]
 [1 5 3 7]]


In [17]:
a_11_33 = a[1:3, 1:3].copy()
print(a_11_33)

[[1 6]
 [0 3]]


In [18]:
a_11_33[0, 0] = 99
a_11_33[0, 1] = 88
a_11_33[1, 0] = 77
a_11_33[1, 1] = 66

In [21]:
print(a_11_33, end="\n\n")
print(a)

[[99 88]
 [77 66]]

[[4 0 3 7]
 [9 1 6 3]
 [6 0 3 2]
 [1 5 3 7]]
