# NumPy Dizi Yeniden Şekillendirme

In [1]:
import numpy as np

In [2]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
print(np.arange(1, 10).shape)

(9,)


In [4]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
print(np.arange(1,10).reshape((3,3)).shape)

(3, 3)


## Tek boyutlu diziyi (vektörü) iki boyutlu hale getirme

In [6]:
v = np.arange(1, 10)

In [7]:
print(v)

[1 2 3 4 5 6 7 8 9]


In [8]:
print(v.ndim)

1


### Yukarıda görüldüğü gibi v tek boyutlu ve 9 elemanlı bir dizi
Şimdi bu diziyi 2 boyutlu hale getirmek için `reshape` uygulayacağız

In [9]:
v_r = v.reshape((1,9))

In [10]:
print(v_r)

[[1 2 3 4 5 6 7 8 9]]


In [12]:
print(v_r.ndim)

2


# NumPy Dizi Birleştirme