# NumPy Dizi Yeniden Şekillendirme

In [1]:
import numpy as np

In [2]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
print(np.arange(1, 10).shape)

(9,)


In [4]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
print(np.arange(1,10).reshape((3,3)).shape)

(3, 3)


## Tek boyutlu diziyi (vektörü) iki boyutlu hale getirme

In [6]:
v = np.arange(1, 10)

In [7]:
print(v)

[1 2 3 4 5 6 7 8 9]


In [8]:
print(v.ndim)

1


### Yukarıda görüldüğü gibi v tek boyutlu ve 9 elemanlı bir dizi
Şimdi bu diziyi 2 boyutlu hale getirmek için `reshape` uygulayacağız

In [9]:
v_r = v.reshape((1,9))

In [10]:
print(v_r)

[[1 2 3 4 5 6 7 8 9]]


In [11]:
print(v_r.ndim)

2


# NumPy Dizi Birleştirme

In [12]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [13]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

## İki boyutlu matrisleri birleştirme

In [15]:
x_23 = np.array([[1, 2, 3],
                 [4, 5, 6]])
x_43 = np.concatenate([x_23, x_23])

In [18]:
print(x_23)
print(x_23.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [19]:
print(x_43)
print(x_43.shape)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
(4, 3)


### Görüldüğü üzere iki matris satır bazında birleştirildi
Böylece 2x3 iki matrisin alt alta koyulmasıyla 4x3 bir matris elde edildi. Şimdi sütun bazında birleştirme yapalım

In [22]:
x_26 = np.concatenate([x_23, x_23], axis=1)

In [23]:
print(x_26)
print(x_26.shape)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
(2, 6)


# NumPy Dizi Ayırma

In [24]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])

### x dizisini 3. elemana dek ayır, sonra 5. elemana dek ayır

In [26]:
np.split(x, [3, 5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

## İki boyutlu ayırma

In [28]:
m = np.arange(16).reshape(4,4)
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [31]:
ust, alt = np.vsplit(m, [2])

In [32]:
print(ust)

[[0 1 2 3]
 [4 5 6 7]]


In [33]:
print(alt)

[[ 8  9 10 11]
 [12 13 14 15]]


In [34]:
sol, sag = np.hsplit(m, [2])

In [35]:
print(sol)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [36]:
print(sag)

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
