In [1]:
import numpy as np

# Özellikler
*  **ndim**: boyut sayısı
* **shape**: boyut bilgisi
*  **size**: toplam eleman sayısı
* **dtype**: dizi veri tipi

## Toplam 10 elemandan oluşan 1 boyutlu dizi

In [2]:
np.random.randint(10, size = 10)

array([6, 5, 8, 6, 4, 9, 1, 1, 4, 6])

In [3]:
a = np.random.randint(10, size = 10)

In [4]:
print(a.ndim)

1


In [5]:
print(a.shape)

(10,)


In [6]:
print(a.dtype)

int64


## 3x5'lik matris

In [7]:
b = np.random.randint(10, size = (3,5))

In [8]:
print(b)

[[1 2 1 4 1]
 [3 9 0 6 7]
 [1 6 2 3 5]]


In [9]:
print(b.ndim)

2


In [10]:
print(b.shape)

(3, 5)


In [11]:
print(b.size)

15


In [12]:
print(b.dtype)

int64
